# Generated by Django 5.0.1 on 2024-01-24 17:11

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('time_perform', models.DurationField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('service', 'price')},
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('isWork', models.BooleanField(default=False)),
                ('start_work_at', models.TimeField()),
                ('end_work', models.TimeField()),
                ('status', models.CharField(choices=[('Working', 'On'), ('Off Work', 'Off'), ('Busy', 'Busy'), ('Available', 'Available'), ('Relax', 'Metime')], default='Off Work', max_length=12)),
                ('picture', models.BinaryField(editable=True, null=True)),
                ('content_type', models.CharField(help_text='The MIMEType of the file', max_length=256, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Khach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('first_comes', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('WebSite', 'Online'), ('Cancel', 'Cancel')], default='WebSite', max_length=12)),
                ('day_comes', models.DateField()),
                ('time_at', models.TimeField()),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('services', models.ManyToManyField(blank=True, related_name='khachs', to='ledger.service')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='khachs', to='ledger.technician')),
            ],
            options={
                'ordering': ['full_name', '-day_comes'],
                'unique_together': {('full_name', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayoff', to='ledger.technician')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'Text must be greater than 1 characters')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_chats', to='ledger.khach')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_chats', to='ledger.technician')),
            ],
        ),
    ]
