# Generated by Django 5.0.1 on 2025-03-27 20:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('chat', 'client')},
        ),
        migrations.AddField(
            model_name='chat',
            name='isNew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='like',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_chats', to='ledger.khach'),
        ),
        migrations.AlterField(
            model_name='historicalkhach',
            name='full_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='historicaltechnician',
            name='time_come_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='khach',
            name='full_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='like',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_chats', to='ledger.khach'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='time_come_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('chat', 'client'), ('chat', 'owner')},
        ),
        migrations.CreateModel(
            name='KhachVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_spent', models.DecimalField(decimal_places=2, editable=False, max_digits=7, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khachvisits', to='ledger.khach')),
                ('services', models.ManyToManyField(to='ledger.service')),
            ],
        ),
        migrations.CreateModel(
            name='TechWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.technician')),
            ],
        ),
    ]
