# Generated by Django 5.0.1 on 2025-01-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_technician_time_come_in'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='khach',
            unique_together=set(),
        ),
    ]
