# Generated by Django 5.0.1 on 2024-01-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_khach_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khach',
            name='status',
            field=models.CharField(choices=[('WebSite', 'Online'), ('Cancel', 'Cancel'), ('Anyone', 'Anyone')], default='WebSite', max_length=20),
        ),
    ]
