# Generated by Django 5.0.1 on 2025-03-29 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2025, 3, 29, 8, 59, 4, 894581)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Nail Enhancement', 'Nail'), ('Manicure', 'Mani'), ('Pedicure', 'Pedi'), ('Wax', 'Wax'), ('Fix', 'Fix')], default='Nail Enhancement', help_text='Choose one of the categories.', max_length=20),
        ),
    ]
