# Generated by Django 5.0.1 on 2025-01-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_khach_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='khach',
            unique_together={('full_name', 'phone')},
        ),
    ]
