# Generated by Django 5.0.1 on 2024-01-30 22:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_khach_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_chats', to='ledger.khach'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_chats', to='ledger.technician'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, 'Say something!!')]),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='khach',
            name='status',
            field=models.CharField(choices=[('WebSite', 'Online'), ('Anyone', 'Anyone'), ('Cancel', 'Cancel')], default='WebSite', help_text='choice Anyone for alternate! or cancel your appointment.', max_length=20),
        ),
        migrations.CreateModel(
            name='TakeTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_at', models.TimeField(auto_now_add=True)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ser_turn', to='ledger.service')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_turn', to='ledger.technician')),
            ],
        ),
    ]
