# Generated by Django 5.0.1 on 2025-01-27 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_khach_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khach',
            name='payment',
        ),
    ]
