# Generated by Django 5.0.1 on 2025-03-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_supply_date_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='supply',
            unique_together={('title',)},
        ),
    ]
