# Generated by Django 5.0.1 on 2025-03-14 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_like_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_chats', to='ledger.khach'),
        ),
    ]
