# Generated by Django 5.0.1 on 2025-03-13 22:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_like_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('chat', 'client'), ('chat', 'owner')},
        ),
    ]
