# Generated by Django 5.0.1 on 2025-03-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_supply_date_alter_supply_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
