# Generated by Django 5.0.1 on 2025-01-28 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_remove_khach_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='isWork',
        ),
        migrations.AddField(
            model_name='technician',
            name='vacation_end',
            field=models.DateField(blank=True, help_text='End vacation, back work!', null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='vacation_start',
            field=models.DateField(blank=True, help_text='Start vacation', null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='work_days',
            field=models.CharField(default='1111110', help_text='MTWTFSS: 1 for work, 0 for off', max_length=7),
        ),
        migrations.AlterField(
            model_name='service',
            name='time_perform',
            field=models.DurationField(default=datetime.timedelta(seconds=2700)),
        ),
        migrations.AlterField(
            model_name='technician',
            name='status',
            field=models.CharField(choices=[('Working', 'On'), ('Off Work', 'Off'), ('Available', 'Available')], default='Working', max_length=12),
        ),
    ]
