# Generated by Django 5.0.1 on 2025-02-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_remove_technician_iswork_technician_vacation_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='status',
        ),
        migrations.AddField(
            model_name='technician',
            name='isWork',
            field=models.BooleanField(default=False),
        ),
    ]
