# Generated by Django 5.0.1 on 2025-02-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_remove_technician_status_technician_iswork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khach',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Online'), ('Anyone', 'Anyone'), ('Cancel', 'Cancel')], default='Confirmed', help_text='choice Anyone for alternate! or cancel your appointment.', max_length=20),
        ),
    ]
