# Generated by Django 5.0.1 on 2025-03-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_alter_like_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.technician')),
            ],
        ),
    ]
