# Generated by Django 5.0.1 on 2025-03-31 21:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_khachvisit_technician'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khachvisit',
            old_name='date',
            new_name='day_comes',
        ),
        migrations.AddField(
            model_name='khachvisit',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Online'), ('Anyone', 'Anyone'), ('Cancel', 'Cancel')], default='Confirmed', help_text='Choose anyone as an alternate!', max_length=20),
        ),
        migrations.AddField(
            model_name='khachvisit',
            name='time_at',
            field=models.TimeField(default=datetime.datetime(2025, 3, 31, 21, 44, 43, 724976)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='khachvisit',
            name='services',
            field=models.ManyToManyField(blank=True, to='ledger.service'),
        ),
        migrations.AlterField(
            model_name='khachvisit',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='khachvisits', to='ledger.technician'),
        ),
    ]
