# Generated by Django 5.0.1 on 2025-04-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_rename_date_khachvisit_day_comes_khachvisit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
