# Generated by Django 5.0.1 on 2025-02-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_alter_khach_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='picture',
            field=models.ImageField(null=True, upload_to='tech_pictures/'),
        ),
    ]
