# Generated by Django 5.0.1 on 2025-03-18 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_techworkday'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_spent', models.DecimalField(decimal_places=2, editable=False, max_digits=7, null=True)),
                ('khach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khachvisits', to='ledger.khach')),
                ('services', models.ManyToManyField(null=True, to='ledger.service')),
            ],
        ),
    ]
