# Generated by Django 5.0.1 on 2025-03-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_khachvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachvisit',
            name='services',
            field=models.ManyToManyField(to='ledger.service'),
        ),
    ]
