# Generated by Django 5.0.1 on 2025-02-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_alter_technician_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taketurn',
            name='services',
        ),
        migrations.RemoveField(
            model_name='taketurn',
            name='tech',
        ),
        migrations.AddField(
            model_name='technician',
            name='date_go_work',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DayOff',
        ),
        migrations.DeleteModel(
            name='TakeTurn',
        ),
    ]
