# Generated by Django 5.0.1 on 2025-04-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_chat_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khachvisit',
            options={'ordering': ['-day_comes']},
        ),
    ]
