# Generated by Django 5.0.1 on 2025-03-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_alter_khachvisit_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khachvisit',
            old_name='khach',
            new_name='client',
        ),
    ]
