# Generated by Django 5.0.1 on 2025-02-05 21:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_remove_taketurn_services_remove_taketurn_tech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_chats', to='ledger.khach'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tech_chats', to='ledger.technician'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, "What's your message.")]),
        ),
    ]
