# Generated by Django 5.0.1 on 2025-04-16 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_alter_khachvisit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.TextField(max_length=800, validators=[django.core.validators.MinLengthValidator(1, "What's your message.")]),
        ),
        migrations.AlterField(
            model_name='historicalkhach',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter your email for booking confirmations.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='khach',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter your email for booking confirmations.', max_length=50, null=True),
        ),
    ]
