# Generated by Django 5.0.1 on 2025-03-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_rename_khach_khachvisit_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khachvisit',
            old_name='client',
            new_name='khach',
        ),
    ]
