# Generated by Django 5.0.1 on 2025-02-05 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_alter_chat_client_alter_chat_tech_alter_chat_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_chats', to='ledger.khach'),
        ),
    ]
