# Generated by Django 5.0.1 on 2025-05-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_alter_service_options_service_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Nail Enhancement', 'Nail'), ('Manicure', 'Mani'), ('Pedicure', 'Pedi'), ('Wax', 'Wax'), ('YFix', 'Yfix')], default='Nail Enhancement', help_text='Choose one of the categories.', max_length=20),
        ),
    ]
