# Generated by Django 5.0.1 on 2025-03-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_rename_khach_khachvisit_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='isNew',
            field=models.BooleanField(default=True),
        ),
    ]
