# Generated by Django 5.0.1 on 2025-06-02 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltechnician',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about the technician', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicaltechnician',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience in the field'),
        ),
        migrations.AddField(
            model_name='historicaltechnician',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 2), editable=False, help_text='Date when the technician was hired'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about the technician', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience in the field'),
        ),
        migrations.AddField(
            model_name='technician',
            name='hire_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 6, 2, 23, 28, 17, 34072), help_text='Date when the technician was hired'),
            preserve_default=False,
        ),
    ]
