# Generated by Django 5.0.1 on 2025-02-06 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_alter_chat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ledger.chat'),
        ),
    ]
