# Generated by Django 5.0.1 on 2025-03-24 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_chat_isnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkhach',
            name='full_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='khach',
            name='full_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
