# Generated by Django 5.0.1 on 2025-06-06 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_historicaltechnician_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('chat', 'client'), ('chat', 'owner')},
        ),
        migrations.AddField(
            model_name='historicaltechnician',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_technicians', to='ledger.technician'),
        ),
        migrations.AddField(
            model_name='technician',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('chat', 'client'), ('chat', 'owner'), ('client', 'technician')},
        ),
    ]
