# Generated by Django 5.0.1 on 2025-02-09 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_chat_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khach',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter your email for booking confirmations.', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='khach',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Online'), ('Anyone', 'Anyone'), ('Cancel', 'Cancel')], default='Confirmed', help_text='Choose anyone as an alternate!', max_length=20),
        ),
        migrations.AlterField(
            model_name='khach',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khachs', to='ledger.technician'),
        ),
    ]
