# Generated by Django 5.0.1 on 2025-06-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_alter_like_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkhach',
            name='upset_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='khach',
            name='upset_button',
            field=models.BooleanField(default=False),
        ),
    ]
