# Generated by Django 5.0.1 on 2025-06-08 14:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_historicalkhach_upset_button_khach_upset_button'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complimentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Is this complimentary available for clients?')),
                ('category', models.CharField(choices=[('Drink', 'Drink'), ('Snack', 'Snack'), ('Gift', 'Gift')], default='Drink', help_text='Choose a category for the complimentary item.', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complimentaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('title', 'category')},
            },
        ),
    ]
