# Generated by Django 5.0.1 on 2025-02-11 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_alter_khach_email_alter_khach_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='ledger.chat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_chats', to='ledger.khach')),
            ],
            options={
                'unique_together': {('chat', 'client')},
            },
        ),
    ]
