# Generated by Django 5.0.1 on 2025-06-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0017_complimentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='complimentary',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a photo for the complimentary item.', null=True, upload_to='complimentaries/'),
        ),
    ]
