# Generated by Django 5.0.1 on 2025-02-11 22:38

import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0017_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalKhach',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, help_text='Enter your email for booking confirmations.', max_length=40, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('first_comes', models.DateTimeField(blank=True, editable=False)),
                ('desc', models.TextField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('Confirmed', 'Online'), ('Anyone', 'Anyone'), ('Cancel', 'Cancel')], default='Confirmed', help_text='Choose anyone as an alternate!', max_length=20)),
                ('day_comes', models.DateField()),
                ('time_at', models.TimeField()),
                ('birthday', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledger.technician')),
            ],
            options={
                'verbose_name': 'historical khach',
                'verbose_name_plural': 'historical khachs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
