# Generated by Django 5.0.1 on 2025-02-11 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_historicalkhach'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalKhach',
        ),
    ]
