# Generated by Django 5.0.1 on 2025-06-14 23:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_complimentary_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpiColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(2)])),
                ('hex_code', models.CharField(help_text='Hex code for the color (e.g., #FF5733)', max_length=7)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opi_colors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'hex_code')},
            },
        ),
        migrations.CreateModel(
            name='UpSetButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mood', models.CharField(choices=[('Smile', 'Smile'), ('Upset', 'Upset'), ('Angry', 'Angry'), ('Frustrated', 'Frustrated')], default='Smile', help_text='Mood of the client when they pressed the button.', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upset_buttons', to='ledger.khach')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upset_buttons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Optional note for the favorite.', max_length=250, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='ledger.khach')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_clients', to='ledger.technician')),
                ('color', models.ForeignKey(blank=True, help_text='Optional color for the favorite.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_clients', to='ledger.opicolor')),
            ],
            options={
                'unique_together': {('client', 'technician')},
            },
        ),
    ]
