# Generated by Django 5.0.1 on 2025-06-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0019_opicolor_upsetbutton_clientfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opicolor',
            name='owner',
        ),
    ]
