# Generated by Django 5.0.1 on 2025-02-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0020_historicalkhach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
