# Generated by Django 5.0.1 on 2025-06-14 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0020_remove_opicolor_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientfavorite',
            unique_together=set(),
        ),
    ]
