# Generated by Django 5.0.1 on 2025-06-27 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0021_alter_clientfavorite_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upsetbutton',
            name='client',
        ),
        migrations.RemoveField(
            model_name='upsetbutton',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='upsetbutton',
            name='owner',
        ),
        migrations.AddField(
            model_name='khachvisit',
            name='isPaid',
            field=models.BooleanField(default=False, help_text='Has the client paid for this visit?'),
        ),
        migrations.AlterField(
            model_name='clientfavorite',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Optional note for the favorite technician.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_clients', to='ledger.technician'),
        ),
    ]
