# Generated by Django 5.0.1 on 2025-08-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0022_remove_upsetbutton_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltechnician',
            name='is_accept_booking',
            field=models.BooleanField(default=True, help_text='Is the technician accepting new bookings?'),
        ),
        migrations.AddField(
            model_name='technician',
            name='is_accept_booking',
            field=models.BooleanField(default=True, help_text='Is the technician accepting new bookings?'),
        ),
    ]
