# Generated by Django 5.0.1 on 2025-02-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0022_historicaltechnician'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('Nail', 'Nail'), ('Hair', 'Hair'), ('Wax', 'Wax'), ('Feet', 'Feet')], default='Nail', help_text='Choose one of the categories.', max_length=15, null=True),
        ),
    ]
