# Generated by Django 5.0.1 on 2025-08-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0023_historicaltechnician_is_accept_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientfavorite',
            name='technician',
        ),
    ]
