# Generated by Django 5.0.1 on 2025-08-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0024_remove_clientfavorite_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachvisit',
            name='get_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
