# Generated by Django 5.0.1 on 2025-11-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0025_khachvisit_get_paid_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ['time_come_in', 'name']},
        ),
    ]
