# Generated by Django 5.0.1 on 2026-01-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0026_alter_technician_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='techworkday',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='techworkday',
            unique_together={('tech', 'day_of_week')},
        ),
    ]
