# Generated by Django 5.0.1 on 2026-06-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0027_techworkday_is_working_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='techworkday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='techworkday',
            name='date',
            field=models.DateField(blank=True, help_text='Specific date for this work schedule. Leave blank for recurring weekly schedule.', null=True),
        ),
        migrations.AddField(
            model_name='techworkday',
            name='notes',
            field=models.CharField(blank=True, help_text="Optional notes for this work day (e.g., 'Morning shift only').", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='techworkday',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='techworkday',
            name='is_working',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='techworkday',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='techworkday',
            constraint=models.UniqueConstraint(condition=models.Q(('date__isnull', True)), fields=('tech', 'day_of_week'), name='unique_tech_date'),
        ),
        migrations.AddConstraint(
            model_name='techworkday',
            constraint=models.UniqueConstraint(condition=models.Q(('date__isnull', False)), fields=('tech', 'date'), name='unique_tech_date_specific'),
        ),
    ]
