# Generated by Django 5.0.1 on 2026-06-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0028_techworkday_date_and_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachvisit',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Online'), ('Phone', 'Phone'), ('Anyone', 'Anyone'), ('Cancel', 'Cancel')], default='Confirmed', help_text='Choose anyone as an alternate!', max_length=20),
        ),
    ]
